#CXX = clang++
SDL = -framework SDL2 -framework SDL2_image
# If your compiler is a bit older you may need to change -std=c++11 to -std=c++0x
CXXFLAGS += -Wall -c -std=c++11 -I /System/Library/Frameworks/SDL2.framework/Headers
CXXFLAGS += -Wall -c -std=c++11 -I /System/Library/Frameworks/SDL2_image.framework/Headers
LDFLAGS += $(SDL) -F /Library/Frameworks
EXE = SDL_Lesson0

all: $(EXE)

$(EXE): main.o
	$(CXX) $(LDFLAGS) $< -o $@

main.o: main.cpp
	$(CXX) $(CXXFLAGS) $< -o $@

#Render.o: Render.cpp Render.h
#	$(CXX) $(CXXFLAGS) $< -o $@

clean:
	rm *.o && rm $(EXE)